### ISSUE TITLE
Как можно узнать Drop Item ID's? 

### ISSUE THREAD

**Issue by MAX1MDEV** [koperniki/SteamDroplerApi#1]
Как можно узнать айди дропа, без реверсирования приложения? (лень)

**Comment by koperniki** [comment]
https://mipped.com/f/threads/vybivaem-drop-s-igr-steam.14367/
ищи сообщения связанные с консолью steam

**Comment by MAX1MDEV** [comment]
я видел этот пост, но как собственно получить для других игр?
